version: '3'

services:
  influxdb:
    image: influxdb:2.6-alpine
    # env_file:
    #   - influxv2.env
    volumes:
      # Mount for influxdb data directory and configuration
      - ./data/influxdbv2:/var/lib/influxdb2:rw
    ports:
      - "8086:8086"

  telegraf:
    image: telegraf:1.25-alpine
    depends_on:
      - influxdb
    volumes:
      # Mount for telegraf config
      - ./data/telegraf/mytelegraf.conf:/etc/telegraf/telegraf.conf:ro
    # env_file:
    #   - influxv2.env
    
  grafana:
   image: grafana/grafana
   container_name: grafana-server
   restart: always
   depends_on:
     - influxdb
   environment:
     - GF_SECURITY_ADMIN_USER=admin
     - GF_SECURITY_ADMIN_PASSWORD=admin
     - GF_INSTALL_PLUGINS=
   links:
     - influxdb
   ports:
     - '3000:3000'
   volumes:
     - ./data/grafana:/var/lib/grafana

volumes:
  influxdbv2:
