version: '3'

services:
  example-api:
    build:
      context: ../
      dockerfile: ./Dockerfile
    ports:
      - '2223:2223'
    hostname: example-api
    environment:
      - OTEL_GRPC_COLLECTOR_ADDRESS=telegraf:4317

  influxdb:
    container_name: influxdb
    image: influxdb:2.6-alpine
    volumes:
      - ./data/influx:/var/lib/influxdb2:rw
      - ./config/influx:/etc/influxdb2
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_ORG=NS
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminadmin
      - DOCKER_INFLUXDB_INIT_BUCKET=sample
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=12345678


  telegraf:
    container_name: telegraf
    image: telegraf:1.25-alpine
    depends_on:
      - influxdb
    volumes:
      - ./config/telegraf/mytelegraf.conf:/etc/telegraf/telegraf.conf:ro
    
  grafana:
   image: grafana/grafana
   container_name: grafana-server
   restart: always
   depends_on:
     - influxdb
   environment:
     - GF_SECURITY_ADMIN_USER=admin
     - GF_SECURITY_ADMIN_PASSWORD=admin
     - GF_INSTALL_PLUGINS=
   links:
     - influxdb
   ports:
     - '3000:3000'
   volumes:
     - ./data/grafana:/var/lib/grafana
   user: "472:472"

volumes:
  influxdbv2:
